"""upload settings

Revision ID: 880f080648de
Revises: 5b1a142dc271
Create Date: 2026-08-15 20:35:19.357542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '880f080648de'
down_revision: Union[str, Sequence[str], None] = '5b1a142dc271'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('max_upload_bytes', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upload_settings')
    # ### end Alembic commands ###
