"""room is_dm flag for direct messages

Revision ID: 9ca717f837c2
Revises: 9484fbd1cb3a
Create Date: 2026-08-19 15:50:25.781735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ca717f837c2'
down_revision: Union[str, Sequence[str], None] = '9484fbd1cb3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default backfills existing rows; dropped right after since the
    # model itself only sets a Python-side default (see is_archived above).
    op.add_column(
        'rooms', sa.Column('is_dm', sa.Boolean(), nullable=False, server_default=sa.false())
    )
    op.alter_column('rooms', 'is_dm', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'is_dm')
    # ### end Alembic commands ###
