"""add custom emoji

Revision ID: a318850726ee
Revises: 319c30e24cd9
Create Date: 2026-08-28 20:34:27.293658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a318850726ee'
down_revision: Union[str, Sequence[str], None] = '319c30e24cd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_emoji',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('shortcode', sa.String(length=30), nullable=False),
    sa.Column('storage_filename', sa.String(length=64), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_emoji_shortcode'), 'custom_emoji', ['shortcode'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_custom_emoji_shortcode'), table_name='custom_emoji')
    op.drop_table('custom_emoji')
    # ### end Alembic commands ###
