"""user appear_offline presence override

Revision ID: f0f6e494454a
Revises: e849b2efb79b
Create Date: 2026-08-16 15:04:50.204291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0f6e494454a'
down_revision: Union[str, Sequence[str], None] = 'e849b2efb79b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('appear_offline', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'appear_offline')
    # ### end Alembic commands ###
