"""hide DM conversations per-participant

Revision ID: f3f255da9c96
Revises: 9ca717f837c2
Create Date: 2026-08-19 16:36:28.332581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3f255da9c96'
down_revision: Union[str, Sequence[str], None] = '9ca717f837c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_memberships', sa.Column('hidden_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room_memberships', 'hidden_at')
    # ### end Alembic commands ###
