"""room membership last_read_at for unread indicators

Revision ID: f9eff917e5b3
Revises: f0f6e494454a
Create Date: 2026-08-16 20:14:32.449934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9eff917e5b3'
down_revision: Union[str, Sequence[str], None] = 'f0f6e494454a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_memberships', sa.Column('last_read_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room_memberships', 'last_read_at')
    # ### end Alembic commands ###
